package main;

import java.util.LinkedHashMap;
import java.util.Map;


public class Alias {

    private static Map<String, String> language = new LinkedHashMap<>();

    public static void initLanguage () {
        language.put("Australia","Австралия");
        language.put("Austria","Австрия");
        language.put("Azerbaijan","Азербайджан");
        language.put("Albania","Албания");
        language.put("Algeria","Алжир");
        language.put("Angola","Ангола");
        language.put("Andorra","Андорра");
        language.put("Antigua and Barbuda","Антигуа и Барбуда");
        language.put("Argentina","Аргентина");
        language.put("Armenia","Армения");
        language.put("Afghanistan","Афганистан");
        language.put("Bahamas","Багамские Острова");
        language.put("Bangladesh","Бангладеш");
        language.put("Barbados","Барбадос");
        language.put("Bahrain","Бахрейн");
        language.put("Belize","Белиз");
        language.put("Belarus","Белоруссия");
        language.put("Belgium","Бельгия");
        language.put("Benin","Бенин");
        language.put("Bulgaria","Болгария");
        language.put("Bolivia","Боливия");
        language.put("Bosnia and Herzegovina","Босния и Герцеговина");
        language.put("Botswana","Ботсвана");
        language.put("Brazil","Бразилия");
        language.put("Brunei","Бруней");
        language.put("Burkina Faso","Буркина-Фасо");
        language.put("Burundi","Бурунди");
        language.put("Butane","Бутан");
        language.put("Vanuatu","Вануату");
        language.put("United Kingdom","Великобритания");
        language.put("Hungary","Венгрия");
        language.put("Venezuela","Венесуэла");
        language.put("East Timor","Восточный Тимор");
        language.put("Vietnam","Вьетнам");
        language.put("Gabon","Габон");
        language.put("Haiti","Гаити");
        language.put("Guyana","Гайана");
        language.put("Gambia","Гамбия");
        language.put("Ghana","Гана");
        language.put("Guatemala","Гватемала");
        language.put("Guinea","Гвинея");
        language.put("Guinea-Bissau","Гвинея-Бисау");
        language.put("Germany","Германия");
        language.put("Honduras","Гондурас");
        language.put("Grenada","Гренада");
        language.put("Greece","Греция");
        language.put("Georgia","Грузия");
        language.put("Denmark","Дания");
        language.put("Djibouti","Джибути");
        language.put("Dominica","Доминика");
        language.put("Dominican Republic","Доминиканская Республика");
        language.put("DR Congo","ДР Конго");
        language.put("Egypt","Египет");
        language.put("Zambia","Замбия");
        language.put("Zimbabwe","Зимбабве");
        language.put("Israel","Израиль");
        language.put("India","Индия");
        language.put("Indonesia","Индонезия");
        language.put("Jordan","Иордания");
        language.put("Iraq","Ирак");
        language.put("Iran","Иран");
        language.put("Ireland","Ирландия");
        language.put("Iceland","Исландия");
        language.put("Spain","Испания");
        language.put("Italy","Италия");
        language.put("Yemen","Йемен");
        language.put("Cape Verde","Кабо-Верде");
        language.put("Kazakhstan","Казахстан");
        language.put("Cambodia","Камбоджа");
        language.put("Cameroon","Камерун");
        language.put("Canada","Канада");
        language.put("Qatar","Катар");
        language.put("Kenya","Кения");
        language.put("Cyprus","Кипр");
        language.put("Kyrgyzstan","Киргизия");
        language.put("Kiribati","Кирибати");
        language.put("China","Китай");
        language.put("DPRK","КНДР");
        language.put("Colombia","Колумбия");
        language.put("Comoros Islands","Коморские Острова");
        language.put("Costa Rica","Коста-Рика");
        language.put("Cote d'Ivoire","Кот-д'Ивуар");
        language.put("Cuba","Куба");
        language.put("Kuwait","Кувейт");
        language.put("Laos","Лаос");
        language.put("Latvia","Латвия");
        language.put("Lesotho","Лесото");
        language.put("Liberia","Либерия");
        language.put("Lebanon","Ливан");
        language.put("Libya","Ливия");
        language.put("Lithuania","Литва");
        language.put("Liechtenstein","Лихтенштейн");
        language.put("Luxembourg","Люксембург");
        language.put("Mauritius","Маврикий");
        language.put("Mauritania","Мавритания");
        language.put("Madagascar","Мадагаскар");
        language.put("Malawi","Малави");
        language.put("Malaysia","Малайзия");
        language.put("Mali","Мали");
        language.put("Maldives","Мальдивские Острова");
        language.put("Malta","Мальта");
        language.put("Morocco","Марокко");
        language.put("Marshall Islands","Маршалловы Острова");
        language.put("Mexico","Мексика");
        language.put("Mozambique","Мозамбик");
        language.put("Moldova","Молдавия");
        language.put("Monaco","Монако");
        language.put("Mongolia","Монголия");
        language.put("Myanmar","Мьянма");
        language.put("Namibia","Намибия");
        language.put("Nauru","Науру");
        language.put("Nepal","Непал");
        language.put("Niger","Нигер");
        language.put("Nigeria","Нигерия");
        language.put("Netherlands","Нидерланды");
        language.put("Nicaragua","Никарагуа");
        language.put("New Zealand","Новая Зеландия");
        language.put("Norway","Норвегия");
        language.put("UAE","ОАЭ");
        language.put("Oman","Оман");
        language.put("Pakistan","Пакистан");
        language.put("Palau","Палау");
        language.put("Panama","Панама");
        language.put("Papua New Guinea","Папуа - Новая Гвинея");
        language.put("Paraguay","Парагвай");
        language.put("Peru","Перу");
        language.put("Poland","Польша");
        language.put("Portugal","Португалия");
        language.put("Republic of Congo","Республика Конго");
        language.put("Republic of Korea","Республика Корея");
        language.put("Russia","Россия");
        language.put("Rwanda","Руанда");
        language.put("Romania","Румыния");
        language.put("Salvador","Сальвадор");
        language.put("Samoa","Самоа");
        language.put("San Marino","Сан-Марино");
        language.put("Sao Tome and Principe","Сан-Томе и Принсипи");
        language.put("Saudi Arabia","Саудовская Аравия");
        language.put("North Macedonia","Северная Македония");
        language.put("Seychelles","Сейшельские Острова");
        language.put("Senegal","Сенегал");
        language.put("Saint Vincent and the Grenadines","Сент-Винсент и Гренадины");
        language.put("Saint Kitts and Nevis","Сент-Китс и Невис");
        language.put("Saint Lucia","Сент-Люсия");
        language.put("Serbia","Сербия");
        language.put("Singapore","Сингапур");
        language.put("Syria","Сирия");
        language.put("Slovakia","Словакия");
        language.put("Slovenia","Словения");
        language.put("Solomon Islands","Соломоновы Острова");
        language.put("Somalia","Сомали");
        language.put("Sudan","Судан");
        language.put("Suriname","Суринам");
        language.put("USA","США");
        language.put("Sierra Leone","Сьерра-Леоне");
        language.put("Tajikistan","Таджикистан");
        language.put("Thailand","Таиланд");
        language.put("Tanzania","Танзания");
        language.put("Togo","Того");
        language.put("Tonga","Тонга");
        language.put("Trinidad and Tobago","Тринидад и Тобаго");
        language.put("Tuvalu","Тувалу");
        language.put("Tunisia","Тунис");
        language.put("Turkmenistan","Туркмения");
        language.put("Türkiye","Турция");
        language.put("Uganda","Уганда");
        language.put("Uzbekistan","Узбекистан");
        language.put("Ukraine","Украина");
        language.put("Uruguay","Уругвай");
        language.put("Federated States of Micronesia","Федеративные Штаты Микронезии");
        language.put("Fiji","Фиджи");
        language.put("Philippines","Филиппины");
        language.put("Finland","Финляндия");
        language.put("France","Франция");
        language.put("Croatia","Хорватия");
        language.put("CAR","ЦАР");
        language.put("Chad","Чад");
        language.put("Montenegro","Черногория");
        language.put("Czech Republic","Чехия");
        language.put("Chile","Чили");
        language.put("Switzerland","Швейцария");
        language.put("Sweden","Швеция");
        language.put("Sri Lanka","Шри-Ланка");
        language.put("Ecuador","Эквадор");
        language.put("Equatorial Guinea","Экваториальная Гвинея");
        language.put("Eritrea","Эритрея");
        language.put("Eswatini","Эсватини");
        language.put("Estonia","Эстония");
        language.put("Ethiopia","Эфиопия");
        language.put("South Africa","ЮАР");
        language.put("South Sudan","Южный Судан");
        language.put("Jamaica","Ямайка");
        language.put("Japan","Япония");
    }

    public String languageSwitch (String name) {
        return language.get(name);
    }


}
