name: TrDr
version: '1.1'
main: main.main
api-version: '1.20'

load: STARTUP
authors: [Matva, Drac0shka]
description: Economy plugin for server TrDr
website: later
commands:
  setmoney: {}
  getmoney: {}
